#!/usr/bin/env python3
"""Fail when files unsuitable for a public source repository are present."""
from __future__ import annotations

import re
from pathlib import Path

from _bootstrap import PROJECT_ROOT

# A Windows drive letter or a unix home directory: both leak whoever built this.
LOCAL_PATH = re.compile(r"(?<![A-Za-z])[A-Za-z]:[\\/]|/home/[a-z]|/Users/[A-Za-z]")
TEXT_SUFFIXES = {
    ".tsv", ".md", ".json", ".toml", ".yml", ".yaml", ".py", ".txt", ".bat", ".sh", ".cfg",
}


def local_path_hits(path: Path) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    hits = []
    for number, line in enumerate(text.splitlines(), 1):
        if "://" in line:  # URLs are not filesystem paths
            continue
        if LOCAL_PATH.search(line):
            hits.append(f"{number}: {line.strip()[:80]}")
    return hits


SKIP_DIRECTORIES = {
    ".claude",
    ".git",
    ".venv",
    ".uv-cache",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    "work",
}
PROHIBITED_SUFFIXES = {
    ".nds",
    ".srl",
    ".sav",
    ".dsv",
    ".ml1",
    ".ml2",
    ".pyc",
    ".xls",
    ".xlsx",
}
MAX_SOURCE_FILE_SIZE = 10 * 1024 * 1024


def main() -> None:
    problems: list[str] = []
    for path in PROJECT_ROOT.rglob("*"):
        relative = path.relative_to(PROJECT_ROOT)
        if any(part in SKIP_DIRECTORIES for part in relative.parts):
            continue
        # Locally generated by `uv sync` / any import; already covered by .gitignore.
        if any(part == "__pycache__" or part.endswith(".egg-info") for part in relative.parts):
            continue
        if path.is_dir():
            continue
        suffix = path.suffix.lower()
        if suffix in PROHIBITED_SUFFIXES or path.name.startswith(".state"):
            problems.append(f"prohibited binary: {relative.as_posix()}")
        if path.stat().st_size > MAX_SOURCE_FILE_SIZE:
            problems.append(
                f"large source-tree file ({path.stat().st_size} bytes): {relative.as_posix()}"
            )
        if suffix in TEXT_SUFFIXES:
            for hit in local_path_hits(path):
                problems.append(f"local filesystem path: {relative.as_posix()}:{hit}")

    if problems:
        print("public-tree check failed:")
        for problem in problems:
            print(f"- {problem}")
        raise SystemExit(1)
    print("public-tree check passed")


if __name__ == "__main__":
    main()
